print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "D:/HKU - 1/Blok 3/Unity/git/Eindproject/Assets/Prefabs/Lelie.mb"`)
{		
	file -o "D:/HKU - 1/Blok 3/Unity/git/Eindproject/Assets/Prefabs/Lelie.mb";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "D:/HKU - 1/Blok 3/Unity/git/Eindproject/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";

sysFile -delete "D:/HKU - 1/Blok 3/Unity/git/Eindproject/Temp/CommandPipe";

$donepipeKill = `fopen "D:/HKU - 1/Blok 3/Unity/git/Eindproject/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
